USE master;
GO
CREATE DATABASE EmployeesDB
ON PRIMARY
(
	NAME=EmployeesDB,
	FILENAME='D:\SQLSERVER\Databases\EmployeesDB.mdf',
	SIZE=100MB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=25MB
)
LOG ON
(
	NAME=EmployeesDB_Log,
	FILENAME='D:\SQLSERVER\Databases\EmployeesDB_Log.ldf',
	SIZE=50MB,
	MAXSIZE=500MB,
	FILEGROWTH=50MB
)
COLLATE Latin1_General_CI_AS;
ALTER DATABASE EmployeesDB SET RECOVERY FULL;
ALTER DATABASE EmployeesDB MODIFY FILEGROUP [PRIMARY] DEFAULT;