USE EmployeeDB
BEGIN TRY
	BEGIN TRANSACTION
	INSERT INTO Person (FirstName, LastName) VALUES ('Ivee' , 'Jintalan')
	DELETE FROM Person WHERE FirstName='Hotdog'
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
END CATCH
